name: RRNavigation
options:
  bundleIdPrefix: com.rrnavigation
  deploymentTarget:
    iOS: "15.0"
    macOS: "12.0"
    tvOS: "15.0"
    watchOS: "8.0"
    visionOS: "1.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  defaultScheme: RRNavigation

packages:
  RRFoundation:
    url: https://github.com/rirp53021/rr-swift-foundation.git
    from: 1.9.0
    generateScheme: false
  
  RRPersistence:
    url: https://github.com/rirp53021/rr-swift-persistence.git
    from: 1.1.0
    generateScheme: false

settings:
  SWIFT_VERSION: "5.9"
  ENABLE_TESTING_SEARCH_PATHS: true
  CLANG_ENABLE_MODULES: true
  SWIFT_INSTALL_OBJC_HEADER: false
  BUILD_LIBRARY_FOR_DISTRIBUTION: true
  SWIFT_COMPILATION_MODE: "wholemodule"

targets:
  RRNavigation:
    type: framework
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources/RRNavigation
    dependencies:
      - package: RRFoundation
      - package: RRPersistence
    settings:
      PRODUCT_NAME: RRNavigation
      PRODUCT_BUNDLE_IDENTIFIER: com.rrnavigation.core
      CLANG_ENABLE_MODULES: true
      SWIFT_INSTALL_OBJC_HEADER: false
      BUILD_LIBRARY_FOR_DISTRIBUTION: true
      SWIFT_ENABLE_LIBRARY_EVOLUTION: true
      SWIFT_COMPILATION_MODE: "wholemodule"
      SKIP_INSTALL: false
      DEFINES_MODULE: true
      MACH_O_TYPE: mh_dylib
    info:
      path: Sources/RRNavigation/Info.plist
      properties:
        CFBundleName: RRNavigation
        CFBundleDisplayName: RRNavigation
        CFBundleIdentifier: com.rrnavigation.core
        CFBundleVersion: "1.1.0"
        CFBundleShortVersionString: "1.1.0"
        CFBundlePackageType: FMWK
        CFBundleInfoDictionaryVersion: "6.0"

  RRNavigationTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Tests/RRNavigationTests
    dependencies:
      - target: RRNavigation
    settings:
      PRODUCT_NAME: RRNavigationTests
      PRODUCT_BUNDLE_IDENTIFIER: com.rrnavigation.tests
      GENERATE_INFOPLIST_FILE: true

  RRNavigationDemo:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Demo/RRNavigationDemo
    dependencies:
      - target: RRNavigation
    settings:
      PRODUCT_NAME: RRNavigationDemo
      PRODUCT_BUNDLE_IDENTIFIER: com.rrnavigation.demo
      PRODUCT_TYPE: com.apple.product-type.application
      GENERATE_INFOPLIST_FILE: true
      INFOPLIST_KEY_CFBundleDisplayName: "RRNavigation Demo"
      INFOPLIST_KEY_CFBundleExecutable: RRNavigationDemo
      INFOPLIST_KEY_CFBundleIdentifier: com.rrnavigation.demo
      INFOPLIST_KEY_CFBundleName: RRNavigationDemo
      INFOPLIST_KEY_CFBundlePackageType: APPL
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
      INFOPLIST_KEY_UILaunchScreen_Generation: true
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      ENABLE_PREVIEWS: true
      TARGETED_DEVICE_FAMILY: "1,2"
      DEVELOPMENT_ASSET_PATHS: "\"Demo/RRNavigationDemo/Preview Content\""
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      WRAPPER_EXTENSION: app
      EXECUTABLE_EXTENSION: ""
      EXECUTABLE_NAME: RRNavigationDemo

schemes:
  RRNavigation:
    build:
      targets:
        RRNavigation: all
    test:
      targets:
        RRNavigationTests: all
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  RRNavigationDemo:
    build:
      # IMPORTANTE: deshabilitamos buildImplicitDependencies para controlar el orden
      buildImplicitDependencies: false
      # El orden importa: el primer target será el que Xcode muestre como "tipo" del esquema
      targets:
        RRNavigationDemo: all
        RRNavigation: all
    run:
      # forzamos el ejecutable a la app demo
      executable: RRNavigationDemo
      config: Debug
    test:
      config: Debug
      targets:
        RRNavigationTests: all
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
